spring.application.name=familyAsset
spring.docker.compose.enabled=false
spring.datasource.url=jdbc:mysql://localhost:3308/family_asset?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# mybatis

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=org.swan.familyasset.Entity
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.listener.simple.default-requeue-rejected=false